name: Video Push

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL(HTTP/HTTPS OR Metalink)'
        required: true
      video:
        description: 'Video File Path(Wildcard support)'
        required: true
      title:
        description: 'Release Title'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps: 
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2        

      - name: Install dependence
        run: |
          wget -q https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
          tar xf ffmpeg-master-latest-linux64-gpl.tar.xz 
          sudo mv ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
#          pip install -r requirements.txt

      - name: Start task
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
        run: |
            aria2c --conf-path=./aria2/aria2.conf "${{ github.event.inputs.url }}"
            ./split.sh ${{ github.event.inputs.video }} 2000000000 "-c copy"
            ls  -ll
            openssl enc -aes128 -pbkdf2 -d -in tg_client.aes128 -out tg_client.session -pass env:API_HASH
            openssl enc -aes128 -pbkdf2 -in tg_client.session -out tg_client.aes128 -pass env:API_HASH && rm tg_client.session

#      - name: Update repo
#        env:
#          ACTOR: ${{ github.actor }}
#          REPO: ${{ github.repository }}
#        run: |
#          git config --local user.email "${ACTOR}@users.noreply.github.com"
#          git config --local user.name "${ACTOR}"
#          git add .
#          git commit -m 'update' || exit 0
#          git push origin main
          
#      - name: Delete workflow runs
#        uses: Mattraks/delete-workflow-runs@v2
#        with:
#          token: ${{ github.token }}
#          repository: ${{ github.repository }}
#          retain_days: 1
#          keep_minimum_runs: 6
