name: Video Push

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL(HTTP/HTTPS OR Metalink)'
        required: true
      video:
        description: 'Video File Path(Wildcard support)'
        required: true
      name:
        description: 'file name'
        required: true  
      caption:
        description: 'caption'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps: 
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2        

      - name: Install dependence
        run: |
          wget -q https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
          tar xf ffmpeg-master-latest-linux64-gpl.tar.xz 
          sudo mv ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin && rm -rf ffmpeg-master-latest-linux64-gpl
          pip install -r requirements.txt
          python3 aria2/add_tracker.py

      - name: Process video
        run: |
            aria2c --conf-path=./aria2/aria2.conf "${{ github.event.inputs.url }}"
            mv ${{ github.event.inputs.video }} ./${{ github.event.inputs.caption }}.mp4
            bash split.sh ./${{ github.event.inputs.caption }}.mp4 20000000 "-c copy"
            rm ./${{ github.event.inputs.caption }}.mp4
            ls  -ll

      - name: Start task
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
        run: |
            openssl enc -aes128 -pbkdf2 -d -in tg_client.aes128 -out tg_client.session -pass env:API_HASH
            wget https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg -O poster.jpg
            python3 uploader.py "@ccav_98" "${{ github.event.inputs.caption }}"
            openssl enc -aes128 -pbkdf2 -in tg_client.session -out tg_client.aes128 -pass env:API_HASH && rm tg_client.session

#      - name: Update repo
#        env:
#          ACTOR: ${{ github.actor }}
#          REPO: ${{ github.repository }}
#        run: |
#          git config --local user.email "${ACTOR}@users.noreply.github.com"
#          git config --local user.name "${ACTOR}"
#          git add .
#          git commit -m 'update' || exit 0
#          git push origin main
          
#      - name: Delete workflow runs
#        uses: Mattraks/delete-workflow-runs@v2
#        with:
#          token: ${{ github.token }}
#          repository: ${{ github.repository }}
#          retain_days: 1
#          keep_minimum_runs: 6
